# Generated by Django 5.2.3 on 2025-06-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
