# Generated by Django 5.2.3 on 2025-06-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # pyrefly: ignore  # bad-override
    initial = True

    dependencies = [
        ('brands', '0002_alter_brand_options'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('serie_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Série')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['title'],
            },
        ),
    ]
